config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %i[index show destroy] do
    resources :posts, only: %i[index show new create destroy update] do
      resources :comments, only: %i[new create create destroy update]
      resources :likes, only: %i[new create]
    end
  end
  
  root "users#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.role == 'admin'
      can :manage, :all
    else
      can :destroy, Post do |post|
        post.author == user
      end
      can :destroy, Comment do |comment|
        comment.author_id == user.id
      end
      can :create, Post
      can :create, Comment
      can :create, Like
      can :read, :all
    end
    #   user ||= User.new # guest user (not logged in)
    #   user.admin? ? can :manage, :all : can :read, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  after_save :update_comment_counter

  validates :text, length: { minimum: 10 }

  belongs_to :author, class_name: 'User'
  # , dependent: destroy
  belongs_to :post
  # , dependent: destroy

  private

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  after_save :update_likes_counter

  belongs_to :author, class_name: 'User'
  # , dependent: destroy
  belongs_to :post
  # , dependent: destroy

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  after_save :increment_posts_counter

  belongs_to :author, class_name: 'User'
  # , dependent: destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates_associated :author
  validates_presence_of :author_id
  validates :title, length: { maximum: 250 }
  validates :comments_counter, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, comparison: { greater_than_or_equal_to: 0 }
  validates :text, length: { in: 10..500 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def increment_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,
         #  :validatable,
         :lockable, :timeoutable
  #  , :confirmable

  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true }

  def recent_posts
    posts.includes(:comments, :likes).order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protect_from_forgery prepend: true

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :photo, :bio, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @post = Post.includes(:author, :comments, :likes).find(params[:post_id])
    @comment.author_id = current_user.id
    @comment.post_id = params[:post_id]

    respond_to do |format|
      if @comment.save
        format.html do
          redirect_to user_post_path(user_id: @post.author_id, id: @post.id), notice: 'Comment created successfully!'
        end
      else
        flash.now[:alert] = @comment.errors.full_messages.to_sentence
        format.html { render :new }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @post.decrement!(:comments_counter)
    @comment.destroy!
    redirect_to "/users/#{@post.author_id}/posts/#{@post.id}", notice: 'Success!'
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @post = Post.includes(:comments, :likes).find(params[:post_id])
    @user = current_user
    @like = Like.new(author_id: @user.id, post_id: @post.id)

    respond_to do |format|
      if @like.save
        format.html do
          redirect_to user_post_path(user_id: @post.author_id, id: @post.id), notice: "Your liked #{@post}"
        end
      else
        flash.now[:alert] = @like.errors.full_messages.to_sentence
        format.html { redirect_to @post }
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.includes(:posts, :comments, :likes).find(params[:user_id])
    @posts = Post.all
  end

  def show
    @post = Post.includes(:author, :comments, :likes).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.author_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to user_path(id: @post.author_id), notice: 'Post created successfully!' }
      else
        flash.now[:alert] = @post.errors.full_messages.to_sentence
        format.html { render :new }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    user = User.find(@post.author_id)
    user.posts_counter -= 1
    @post.destroy if @post.present?
    user.save

    # Redirect
    respond_to do |format|
      format.html { redirect_to user_path(id: @post.author_id), notice: 'Post was removed.' }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.includes(:posts, :comments, :likes).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_new.html.erb
<section class="container pt-5">
  <div class="container">
    <h1>Add comments form</h1>
    <%= form_with model: @comment, url: user_post_comments_path, class: "card left" do |form| %>
      <%= form.label :text %> <br>
      <%= form.text_area :text , cols: 30, rows: 10 %> <br>
      <%= form.submit "Submit", class: "btn" %>
    <% end %>
  </div>
</section>

app/views/comments/new.html.erb
<section class="container pt-5">
  <div class="container">
    <h1>Add comments form</h1>
    <%= form_with model: @comment, url: user_post_comments_path, class: "card left" do |form| %>
      <%= form.label :text %> <br>
      <%= form.text_area :text , cols: 30, rows: 10 %> <br>
      <%= form.submit "Submit", class: "btn-info" %>
    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeBlogz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success text-center msg"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger text-center msg"><%= alert %></p>
    <% end %>

    <% if user_signed_in? %>
      <a><%= button_to "Sign out", destroy_user_session_path, method: :delete %></a>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="card m-5"> 
    <div class="justify-content-between">
      <div> 
        <div>
          <h2><%= post.title %></h2> 
          <p><%= post.text %></p>
        </div>
        <div class=" float-right">
          <div class="mb-3 mr-5">
            <span>Comments: <%= post.comments_counter %></span>
            <span class="ml-2">Likes: <%= post.likes_counter %></span>
          </div>
          <div class="d-flex justify-content-end mr-5 mb-3">
            <%= link_to "Add comment", new_user_post_comment_path(user_id: post.author_id, post_id: post.id), class: "btn-info p-1" %>
            <%= form_with model: @like, url: user_post_likes_path(post_id: post.id) do |form| %>
              <%= form.submit "Add Like", class: "btn-info ml-2" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card m-5"> 
    <div>
      <div class="m-3">
        <% post.recent_comments.includes(:author).each do |comment| %>
          <p><%= comment.author.name %>: <%= comment.text %></p>
          <% if can? :update, comment %>
            <%#= link_to "Edit Comment", user_posts_path(user_id: post.author_id, post_id: post.id, comment_id: comment.id), class: "btn btn-info btn-xs round" %>
          <% end %>
          <% if can? :destroy, comment %>
            <%= link_to "Delete Comment", user_post_comment_path(author_id: comment.author_id, post_id: comment.post_id,  id: comment.id), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger btn-xs round" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

app/views/posts/index.html.erb
<div class="card m-5">
  <div class="d-flex justify-content-between">
    <div class="m-1">
      <%# <%= image_tag @user.photo, :height => "150px", :width => "150px" %>
    </div>
    <div class="m-5 flex-grow-1">
      <h1><%= @user.name %></h1>
    </div>
    <div class="mb-2 mr-5 d-flex flex-wrap align-content-end">
      <h5>Number of Posts: <%= @user.posts_counter%></h5>
    </div>
  </div>
</div>

<% if can? :create, Post || @user.id == current_user.id  %>
  <button type="button" class="btn btn-info shadow rounded"><%= link_to "Add Post", new_user_post_path(user_id: @user.id), class: "btn-info" %></button>
<% end %>

<%= link_to "Add Post" , new_user_post_path(user_id: @user.id) if can? :create, @post  %>
<%= button_to "Delete Post", method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, @post || @user.id == current_user.id %>

<%= render @posts.includes(:author, :comments, :likes) %>

app/views/posts/new.html.erb
<section class="container pt-5">
  <div class="container">
    <h1>Add a new post</h1>
    <%= form_with model: @post, url: user_posts_path, class: "card left" do |form| %>
      <%= form.label :title %> <br>
      <%= form.text_field :title %> <br>
      <%= form.label :text %> <br>
      <%= form.text_area :text , cols: 30, rows: 10 %> <br>
      <%= form.submit "Submit", class: "btn-info" %>
    <% end %>
  </div>
</section>

app/views/posts/show.html.erb
<div class="card m-5"> 
  <div class="justify-content-between">
    <div> 
      <div>
        <h2><%= @post.title %> by <%= @post.author.name %></h2>
      </div>
      <div class="mb-3 mr-5 float-right">
        <span>Comments: <%= @post.comments.size %></span>
        <span>Likes: <%= @post.likes.size %></span>
      </div>
      <br>
      <div class="d-block"><p><%= @post.text %></p></div>
    </div>
  </div>
</div>
   
<div class="card m-5"> 
  <div>
    <div class="m-3">
      <% @post.recent_comments.includes(:author).each do |comment| %>
        <p><%= comment.author.name %>: <%= comment.text %></p>
        <% if can? :destroy, comment %>
          <%= link_to "Delete Comment", user_post_comment_path(author_id: comment.author_id, post_id: comment.post_id,  id: comment.id), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger btn-xs round" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<% if user_signed_in? %>
  <div class="card mb-2 bg-light" >
    <div class="d-flex justify-content-between mb-3">
      <div class="m-5">
        <%= image_tag user.photo, :alt => "user_photo", :height => "150px", :width => "150px" %>
      </div>
      <div class="m-5 flex-grow-1">
        <article class="card-body " style="width: 18rem;"> 
          <h1><a><%= link_to user.name, user %></a>
          </h1>
          </article>
      </div>
      <div class="mb-2 mr-5 d-flex flex-wrap align-content-end">
          <h5>Number of Posts: <%= user.posts_counter %>
          </h5>
        </div>
    </div>
  </div>
<% else %>
  <a href="/users/sign_in">Sign In</a>
<% end %>

app/views/users/index.html.erb
<%= render @users.includes(:posts) %>

app/views/users/show.html.erb
<div class="card m-5">
  <div class="d-flex justify-content-between">
    <div class="m-1"><%= image_tag @user.photo, :height => "150px", :width => "150px" %></div>
    <div class="m-5 flex-grow-1"><h1><%= @user.name%></h1></div>
    <div class="mb-2 mr-5 d-flex flex-wrap align-content-end"><h5>Number of Posts: <%= @user.posts_counter%></h5></div>
  </div>
</div>

<div class="card m-5 p-3">
  <h4> Bio </h4>
  <p><%= @user.bio %></p>
</div>
<% @user.recent_posts.each do |post| %>
  <div class="card m-5 p-3">
    <div class="d-flex justify-content-between">
      <div>
        <h3><%= link_to post.title, user_post_path(user_id: post.author_id, id: post.id) %></h3>
        <p><%= post.text %></p>
      </div>
      <div class="mb-3 mr-5">
        <span>Comments: <%= post.comments_counter %></span>
        <span class="ml-2">Likes: <%= post.likes_counter %></span>
      </div>

       <% if @user.id == current_user.id  %>
            <a><%= button_to "Delete Post", users_path, method: :delete, data: { confirm: 'Are you sure?' } %></a>
          <% end %>

    </div>
  </div>
<% end %>

<div class="d-flex justify-content-center pb-5">
  <% if can? :create, @post %>
    <button type="button" class="btn btn-info shadow rounded"><%= link_to "Add Post", new_user_post_path(user_id: @user.id), class: "btn-info" %></button>
  <% end %>
  <button type="button" class="btn btn-info shadow rounded">
    <%= link_to "See all posts", user_posts_path(user_id: @user.id), class: "btn-info" %>
  </button>
  <button type="button" class="btn btn-info shadow rounded">
    <%= link_to "See all users", users_path, class: "btn-info" %>
  </button>
</div>